export default Constraints = {
  SUBTITLE: "Here is the list of all Classes",
  appName: "Student security system",
  SCHEDULE: "Appoinments",
  SCHEDULE_subTitle: "Please select Date",
  UPLOADTXT: "Add Patient Report",
  UPLOADSUBTXT: "You have no record ",
  UPLOADSUBTXT2: "of this patient",
  SPH: "SPH",
  CYL: "CYL",
  AXIS: "AXIS",
  VA: "V/A",
  LEFT: "Left",
  RIGHT: "Right",
  REFRACTIONCARD: "Refraction Card",
  PATIENTDETAILS: "Patient Details",
  TREATMENT: "Treatment",
  DIAGNOSIS: "Diagnosis",
  FOOTERTXT: "Find your patient Reports...",
  CHECKEDOUT: "Checked Out",
  PRESENT: "Present",
  NEXT_BTN: "Next",
  PARENTBTNTXT: "Parent",
  LEAVEHOME: "Leaving Home",
  HOME: "Home",
  ARRIVEDHOME: "Home Arrived",
  FOOTERTXT: "Find your student Attendance...",
  NOTARRIVED: "Not Arrived",
  ONBUS: "On the Bus",
};
export const font = { FONTTIMES: "TIMESR" };
