import { Dimensions, StyleSheet } from "react-native";

export default StyleSheet.create({
  underlineStyleBase: {
    width: 44,
    height: 44,
    backgroundColor: "#F6F3F5",
    borderRadius: 44 / 3,
    fontSize: 20,
    color: "black",
  },
  containerr: {
    width: "80%",
    height: "30%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  sectionStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    alignSelf: "center",
    width: "80%",
    padding: "4%",
    height: 45,
    marginBottom: 10,
    borderRadius: 25,
    backgroundColor: "#F6F3F5",
  },
  input: {
    backgroundColor: "#F6F3F5",
    width: "70%",
    height: 45,
    borderRadius: 25,
    marginBottom: 20,
    alignItems: "center",
  },

  error: {
    borderWidth: 4,
    borderColor: "red",
  },
  forgot_button: {
    height: 30,
    marginBottom: 30,
  },
  loginBtn: {
    width: "50%",
    flexDirection: "row",
    backgroundColor: "#DA2328",
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
  },
  categBtn: {
    width: "60%",
    flexDirection: "row",
    borderRadius: 25,
    height: 50,
    padding: 14,
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    backgroundColor: "#F6F3F5",
  },
  image: {
    marginBottom: 40,
    width: "38%",
    height: "20%",
  },
  labelInputText: {
    textAlign: "left",
    marginVertical: 10,
    fontSize: 13,
  },
  Modal: {
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: "15%",
    backgroundColor: "white",
  },
  modalInnerBtn: {
    width: "13%",
    borderRadius: 25,
    height: "6%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "3%",
    backgroundColor: "orange",
  },
  containerContent: {
    alignItems: "center",
    justifyContent: "center",
  },
  exploreSection: {
    paddingHorizontal: 16,
    paddingTop: 30,
  },
  exploreHeader: {
    fontWeight: "bold",
    marginBottom: 30,
    textAlign: "center",
    fontSize: 18,
  },
  exploreContent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  singleExplore: {
    height: 80,
    width: "28%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 1,
    elevation: 1,
    backgroundColor: "white",
    margin: 1,
    marginBottom: 20,
    borderRadius: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  exploreText: {
    fontSize: 13,
    color: "white",
  },
  buttons: {
    width: 400,
    height: 150,
  },
  passwordContainer: {
    flexDirection: "row",
    backgroundColor: "#F6F3F5",
    borderRadius: 25,
    padding: 12,
    width: "80%",
    height: 45,
    alignItems: "center",
    marginTop: "9%",
  },
  TiName: {
    width: "90%",
    height: 45,
    marginLeft: 6,
  },
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  cartBtnBlue: {
    flexDirection: "row",
    width: "10%",
    borderRadius: 12,
    width: "10%",
    height: 37,
    backgroundColor: "black",
    justifyContent: "center",
    alignItems: "center",
  },
  parentContainer: {
    backgroundColor: "#E9967A",
    height: 300,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderBottomLeftRadius: 2,
  },
  img: {
    alignSelf: "center",
    width: 65,
    borderRadius: 10,
    height: 80,
  },
  outTxt: { color: "transparent", fontWeight: "bold", fontSize: 20 },
  signUpTxt: {
    alignSelf: "center",

    color: "black",
    marginTop: 10,
    fontSize: 22,
  },

  cityTxt: { color: "black", fontWeight: "600", fontSize: 15 },

  forpasword: { color: "white", fontSize: 14 },

  line: {
    height: 1.1,
    marginTop: -2,
    backgroundColor: "white",
  },

  sinupBtn: { fontSize: 16, color: "white" },

  joinUsContainer: {
    borderRadius: 30,

    alignItems: "center",
    justifyContent: "space-evenly",
    height: 110,
    backgroundColor: "#2C2C2C",
    width: Dimensions.get("window").width,
  },
  SocialImg: { width: 50, height: 50, marginLeft: 10 },

  alreadytxtContainer: {
    marginTop: "4%",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    width: Dimensions.get("window").width,
  },
  txtAlready: {
    fontSize: 17,

    color: "black",
    marginRight: 7,
    opacity: 0.6,
  },

  logintXT: { fontSize: 17, color: "#DA2328" },
  loader: {
    fontSize: 16,
    color: "#0000ff",
    marginTop: 10,
  },

  subView: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
  },
  imgContainer: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 95 / 2,
    width: 95,
    height: 95,
    backgroundColor: "#EAC36D",
  },
  icon: { width: 90, height: 90, marginTop: "-6%" },
  subViewTwo: {
    borderTopStartRadius: 70,
    alignItems: "center",
    backgroundColor: "white",
  },
  otpStyle: { width: "85%", marginTop: "20%", height: 51 },
});
